### ISSUE TITLE
Projects host integration

### ISSUE THREAD

**Issue by Das-M-e-e** [Das-M-e-e/tschiraplus#68]
### To-Do:
- [x] Post to host db
- [x] Get from host db (only the signed in users projects)
- [x] Delete from host db
- [ ] Update to host db
