### ISSUE TITLE
Tasks host integration

### ISSUE THREAD

**Issue by Das-M-e-e** [Das-M-e-e/tschiraplus#73]
## To-Do:
- [x] Post tasks to host
- [x] Get tasks from host
- [ ] put/update tasks to host
- [x] delete tasks from host
