### ISSUE TITLE
Implement offline mode

### ISSUE THREAD

**Issue by Das-M-e-e** [Das-M-e-e/tschiraplus#76]
When the host isn't reachable, users should be able to create projects and tasks locally, which are synced with/pushed to the host once its available again.
## To-Do:
- [ ] Create a SyncService class
- [ ] Create method(s) for syncing the local db to the remote db. These method(s) should compare the local entry to the remote entry by the attribute LastUpdated and take the later dated one and write it to both the local and remote db
- [ ] Implement the SyncService in Startup
- [ ] Implement cyclic syncing (every 10 seconds or so)
