### ISSUE TITLE
Put input validation in Services

### ISSUE THREAD

**Issue by Das-M-e-e** [Das-M-e-e/tschiraplus#81]
Currently, the input validation for the form fields in the login and register screen are in their ViewModels. This should be put in the Services-Project.
## To-Do:
- [ ] Create ValidationService in the Services-Project
- [ ] Also create an interface for that
### Write the validation methods for all the fields:
Login: (No need to change anything here, just for completeness)
- [ ] Username/Email field (doesn't really need much of validation, just the check if it exists in the host)
- [ ] Password (doesn't need any validation)
Register:
- [ ] Username field (Use the Regex from the ViewModel)
- [ ] Email field (Use the Regex from the ViewModel)
- [ ] Password field (This needs to be modified: List of common passwords, maybe use a file, surely there are resources online somewhere; Regex: Doesn't recognize . and , as special characters, need to modify)
- [ ] ConfirmPassword field (Just check if it is the same as the Password fields value)
### Implementation:
- [ ] Create an instance of the ValidationService in the ViewModel (Use the Interface for that)
- [ ] In the validation methods, use the service for validation: _validationService.ValidateUsername(Username);
